openapi: 3.0.3
info:
  title: DagsHub API
  description: |
    The api docs are made with SwaggerUI using the OpenAPI 3 specification.
  version: 1.0.1
servers:
- url: https://dagshub.com/api/v1/
security:
- basicAuth: []
- tokenAuth: []
paths:
  /user:
    get:
      tags:
      - User
      summary: Get authenticated user information
      operationId: GetAuthenticatedUser
      responses:
        "200":
          description: successfully retrieved user information
          content:
            application/json:
              example:
                id: 5
                login: Dean
                full_name: Dean Pleban
                avatar_url: https://dagshub.com/avatars/5
                username: Dean
  /users/{username}:
    get:
      tags:
      - User
      summary: Get information about a user
      operationId: getUser
      parameters:
      - name: username
        in: path
        description: A DagsHub username
        required: true
        schema:
          type: string
        example: nirbarazida
      responses:
        "200":
          description: successfully retrieved user information
          content:
            application/json:
              example:
                id: 5
                login: Dean
                full_name: Dean Pleban
                avatar_url: https://dagshub.com/avatars/5
                username: Dean
  /repos/{owner}/{repo}/issues:
    get:
      tags:
      - Issues
      summary: List issues for a repository
      description: "This endpoint may also return pull requests in the response. If\
        \ an issue is a pull request, the object will include a pull_request key."
      operationId: listRepoIssues
      parameters:
      - name: owner
        in: path
        description: owner of the repository
        required: true
        schema:
          type: string
        example: DAGsHub-Official
      - name: repo
        in: path
        description: name of the repository
        required: true
        schema:
          type: string
        example: dagshub-docs
      responses:
        "200":
          description: Successfully retrived the data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Issues'
    post:
      tags:
      - Issues
      summary: Create an issue
      description: Any user with read access to a repository can create an issue.
      operationId: createIssue
      parameters:
      - name: owner
        in: path
        description: owner of the repository
        required: true
        schema:
          type: string
        example: DAGsHub-Official
      - name: repo
        in: path
        description: name of the repository
        required: true
        schema:
          type: string
        example: dagshub-docs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostIssue'
      responses:
        "201":
          description: Successfully created an issue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Issue'
    patch:
      tags:
      - Issues
      summary: Edit an issue
      operationId: editIssue
      parameters:
      - name: owner
        in: path
        description: owner of the repository
        required: true
        schema:
          type: string
        example: DAGsHub-Official
      - name: repo
        in: path
        description: name of the repository
        required: true
        schema:
          type: string
        example: dagshub-docs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchIssue'
      responses:
        "201":
          description: Successfully created an issue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Issue'
  /repos/{owner}/{repo}/issues/{index}:
    get:
      tags:
      - Issues
      summary: Get a single issue
      description: "This endpoint may also return pull requests in the response. If\
        \ an issue is a pull request, the object will include a pull_request key."
      operationId: getIssue
      parameters:
      - name: owner
        in: path
        description: owner of the repository
        required: true
        schema:
          type: string
        example: DAGsHub-Official
      - name: repo
        in: path
        description: name of the repository
        required: true
        schema:
          type: string
        example: dagshub-docs
      - name: index
        in: path
        description: the index of an issue or a pull request
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: Successfully retrived the data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Issue'
  /repos/search:
    get:
      tags:
      - Repository
      summary: Search repositories
      operationId: search
      parameters:
      - name: q
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: uid
        in: query
        description: User ID to specify search whose repositories. Default is 0 and
          search all repositories
        required: false
        style: form
        explode: true
        schema:
          type: integer
          default: 0
      - name: limit
        in: query
        description: Maximum number of repositories in search results.
        required: false
        style: form
        explode: true
        schema:
          type: integer
          default: 10
      - name: page
        in: query
        description: Page number. Default is 1.
        required: false
        style: form
        explode: true
        schema:
          type: integer
          default: 1
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                example:
                  data:
                  - id: 1213
                    owner:
                      id: 6
                      login: DAGsHub-Official
                      full_name: DagsHub Official
                      avatar_url: https://dagshub.com/avatars/6
                      username: DAGsHub-Official
                    name: dagshub-docs
                    full_name: DAGsHub-Official/dagshub-docs
                    description: Official repo for DagsHub documentation.
                    private: false
                    fork: false
                    parent: null
                    empty: false
                    mirror: false
                    size: 458313728
                    html_url: https://dagshub.com/DAGsHub-Official/dagshub-docs
                    ssh_url: ssh://git@dagshub.com:2200/DAGsHub-Official/dagshub-docs.git
                    clone_url: https://dagshub.com/DAGsHub-Official/dagshub-docs.git
                    website: https://dagshub.com/docs
                    stars_count: 4
                    forks_count: 11
                    watchers_count: 1
                    open_issues_count: 2
                    default_branch: main
                    created_at: 2021-02-23T11:53:45Z
                    updated_at: 2022-09-14T09:55:35Z
                  ok: true
                x-content-type: application/json
  /repos/{username}/{repo}:
    get:
      tags:
      - Repository
      summary: Get repository information
      operationId: getRepo
      parameters:
      - name: username
        in: path
        description: A DagsHub username
        required: true
        schema:
          type: string
        example: nirbarazida
      - name: repo
        in: path
        description: name of the repository
        required: true
        schema:
          type: string
        example: dagshub-docs
      responses:
        "200":
          description: repository information successfully retrieved
  /user/repos:
    get:
      tags:
      - Repository
      summary: List your repositories
      description: |
        List repositories that are accessible to the authenticated user.

        This includes repositories owned by the authenticated user, repositories where the authenticated user is a collaborator, and repositories that the authenticated user has access to through an organization membership.
      operationId: listMyRepos
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                example:
                - id: 2942
                  owner:
                    id: 23
                    login: DagsHub
                    full_name: DagsHub
                    avatar_url: https://dagshub.com/avatars/23
                    username: DagsHub
                  name: audio-datasets
                  full_name: DagsHub/audio-datasets
                  description: Open-source audio datasets hosted on DagsHub
                  private: false
                  fork: false
                  parent: null
                  empty: false
                  mirror: true
                  size: 10121216
                  html_url: https://dagshub.com/DagsHub/audio-datasets
                  ssh_url: ssh://git@dagshub.com:2200/DagsHub/audio-datasets.git
                  clone_url: https://github.com/DAGsHub/audio-datasets.git
                  website: ""
                  stars_count: 2
                  forks_count: 2
                  watchers_count: 7
                  open_issues_count: 11
                  default_branch: main
                  created_at: 2021-10-05T16:02:42Z
                  updated_at: 2022-08-22T09:54:12Z
                  permissions:
                    admin: true
                    push: true
                    pull: true
                x-content-type: application/json
    post:
      tags:
      - Repository
      summary: Create
      description: Create a new repository for the authenticated user.
      operationId: createRepo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRepo'
      responses:
        "201":
          description: Created
  /users/{username}/repos:
    get:
      tags:
      - Repository
      summary: List user repositories
      description: List public repositories for the specified user.
      operationId: listUserRepos
      parameters:
      - name: username
        in: path
        description: A DagsHub username
        required: true
        schema:
          type: string
        example: nirbarazida
      responses:
        "200":
          description: Success
  /orgs/{orgname}/repos:
    get:
      tags:
      - Repository
      summary: List organization repositories
      description: List repositories that are accessible to the authenticated user.
      operationId: listOrgRepos
      parameters:
      - name: orgname
        in: path
        description: A DagsHub organization name
        required: true
        schema:
          type: string
        example: DAGsHub-Official
      responses:
        "200":
          description: Success
  /org/{orgname}/repos:
    post:
      tags:
      - Repository
      summary: Create in organization
      description: Create a new repository in this organization. The authenticated
        user must be an **owner** of the specified organization.
      operationId: createOrgRepo
      parameters:
      - name: orgname
        in: path
        description: A DagsHub organization name
        required: true
        schema:
          type: string
        example: DAGsHub-Official
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRepo'
      responses:
        "201":
          description: Created
  /repos/migrate:
    post:
      tags:
      - Repository
      summary: Migrate repository
      description: |
        Migrate a repository from other Git hosting sources for the authenticated user.

        To migrate a repository for a organization, the authenticated user must be a **owner** of the specified organization.
      operationId: migrateRepo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MigrateRepo'
      responses:
        "201":
          description: Created
  /repos/{username}/{repo}/raw/{ref}/{path}:
    get:
      tags:
      - Content
      summary: Download raw content
      description: This method returns the raw content of a file.
      operationId: getRaw
      parameters:
      - name: username
        in: path
        description: A DagsHub username
        required: true
        schema:
          type: string
        example: nirbarazida
      - name: repo
        in: path
        description: name of the repository
        required: true
        schema:
          type: string
        example: dagshub-docs
      - name: ref
        in: path
        description: The name of the commit/branch/tag
        required: true
        schema:
          type: string
          example: master
      - name: path
        in: path
        description: The content path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
  /repos/{username}/{repo}/archive/{ref}/{format}:
    get:
      tags:
      - Content
      summary: Download archive
      description: This method returns archive by given format.
      operationId: getArchive
      parameters:
      - name: username
        in: path
        description: A DagsHub username
        required: true
        schema:
          type: string
        example: nirbarazida
      - name: repo
        in: path
        description: name of the repository
        required: true
        schema:
          type: string
        example: dagshub-docs
      - name: ref
        in: path
        description: The name of the commit/branch/tag
        required: true
        schema:
          type: string
          example: master
      - name: format
        in: path
        description: "The format of archive, either .zip or .tar.gz"
        required: true
        style: simple
        explode: false
        schema:
          type: string
          enum:
          - .zip
          - .tar.gz
      responses:
        "200":
          description: OK
  /repos/{owner}/{repo}/branches:
    get:
      tags:
      - Branches
      summary: List Branches
      operationId: listBranches
      parameters:
      - name: owner
        in: path
        description: owner of the repository
        required: true
        schema:
          type: string
        example: DAGsHub-Official
      - name: repo
        in: path
        description: name of the repository
        required: true
        schema:
          type: string
        example: dagshub-docs
      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
              - name: master
                commit:
                  id: c1c220c4dd6df895965a02b8be575c5e2f78dfd1
                  message: "A commit message. \n"
                  url: Not implemented
                  author:
                    name: Author Name
                    email: author@email.com
                    username: ""
              - name: second-branch
                commit:
                  id: 0a0fdf63c23af6a2836c426c5284136015ec2996
                  message: |
                    A second commit message.
                  url: Not implemented
                  author:
                    name: Author Name
                    email: author@email.com
                    username: ""
  /repos/{owner}/{repo}/branches/{branch}:
    get:
      tags:
      - Branches
      summary: Get Branch
      operationId: getBranch
      parameters:
      - name: owner
        in: path
        description: owner of the repository
        required: true
        schema:
          type: string
        example: DAGsHub-Official
      - name: repo
        in: path
        description: name of the repository
        required: true
        schema:
          type: string
        example: dagshub-docs
      - name: branch
        in: path
        description: branch of the repository
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
                name: :branchname
                commit:
                  id: 0a0fdf63c23af6a2836c426c5284136015ec2996
                  message: |
                    A second commit message.
                  url: Not implemented
                  author:
                    name: Author Name
                    email: author@email.com
                    username: ""
  /repos/{username}/{repo}/collaborators/{collaborator}:
    put:
      tags:
      - Collaborators
      summary: Add user as a collaborator
      operationId: addCollaborator
      parameters:
      - name: username
        in: path
        description: A DagsHub username
        required: true
        schema:
          type: string
        example: nirbarazida
      - name: repo
        in: path
        description: name of the repository
        required: true
        schema:
          type: string
        example: dagshub-docs
      - name: collaborator
        in: path
        description: collaborator username
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/collaborators_collaborator_body'
      responses:
        "200":
          description: Success
    delete:
      tags:
      - Collaborators
      summary: Delete collaborator
      operationId: removeCollaborator
      responses:
        "204":
          description: "No Content, deleted successfully"
        "422":
          description: User does not exist
        "500":
          description: Internal error
  /repos/{username}/{repo}/collaborators:
    get:
      tags:
      - Collaborators
      summary: Get collaborators
      operationId: getCollaborators
      parameters:
      - name: username
        in: path
        description: A DagsHub username
        required: true
        schema:
          type: string
        example: nirbarazida
      - name: repo
        in: path
        description: name of the repository
        required: true
        schema:
          type: string
        example: dagshub-docs
      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
              - id: 3
                username: user1
                login: user1
                full_name: ""
                email: user1@user.com
                avatar_url: https://secure.gravatar.com/avatar/0207f4280f6c1bd45e1a2ed7cb1cca3d
                permissions:
                  admin: false
                  push: true
                  pull: true
  /repos/{owner}/{repo}/commits/{sha}:
    get:
      tags:
      - Commits
      summary: Get a single commit
      operationId: getCommit
      parameters:
      - name: owner
        in: path
        description: owner of the repository
        required: true
        schema:
          type: string
        example: DAGsHub-Official
      - name: repo
        in: path
        description: name of the repository
        required: true
        schema:
          type: string
        example: dagshub-docs
      - name: sha
        in: path
        description: a SHA1 of a commit
        required: true
        schema:
          type: string
          example: 9227a50146b3fd815fe864af99b984c77d06326a
      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
                commit:
                  id: 106201d5de4b7f0cce296b4578747ba43504d152
                  message: |-
                    Merge pull request #65 from drecali/main

                    fix broken Discord invite link and clarify project sharing instructions
                  url: ""
                  author:
                    name: Dean P
                    email: deanp07@gmail.com
                    username: ""
                  committer:
                    name: GitHub
                    email: noreply@github.com
                    username: ""
                  added: null
                  removed: null
                  modified: null
                  timestamp: 2022-08-22T09:53:53Z
                files:
                - filename: CONTRIBUTING.md
                  sha: Not Implemented
                  blob_url: Not Implemented
                  additions: 1
                  deletions: 1
                  changes: 2
                  status: changed
                stats:
                  additions: 1
                  deletions: 1
                  total: 2
                experiment: null
  /repos/{owner}/{repo}/commits/{ref}:
    get:
      tags:
      - Commits
      summary: Get the SHA-1 of a commit reference
      operationId: getCommitSha1
      parameters:
      - name: owner
        in: path
        description: owner of the repository
        required: true
        schema:
          type: string
        example: DAGsHub-Official
      - name: repo
        in: path
        description: name of the repository
        required: true
        schema:
          type: string
        example: dagshub-docs
      - name: ref
        in: path
        description: The name of the commit/branch/tag
        required: true
        schema:
          type: string
          example: master
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
              example: dc20792485ffd49b0bca49f90a8d44a16241b84a
  /repos/{owner}/{repo}/releases:
    get:
      tags:
      - Releases
      summary: List Releases
      operationId: listReleases
      parameters:
      - name: owner
        in: path
        description: owner of the repository
        required: true
        schema:
          type: string
        example: DAGsHub-Official
      - name: repo
        in: path
        description: name of the repository
        required: true
        schema:
          type: string
        example: dagshub-docs
      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
              - id: 1
                tag_name: sometag
                target_commitish: master
                name: awesome-release
                body: Description of the release
                draft: false
                prerelease: false
                author:
                  id: 1
                  username: Author Name
                  login: ""
                  full_name: ""
                  email: author@email.com
                  avatar_url: ""
                created_at: 2020-03-28T13:38:00+03:00
  /repos/{owner}/{repo}/hooks:
    get:
      tags:
      - Webhooks
      summary: List hooks
      operationId: listHooks
      parameters:
      - name: owner
        in: path
        description: owner of the repository
        required: true
        schema:
          type: string
        example: DAGsHub-Official
      - name: repo
        in: path
        description: name of the repository
        required: true
        schema:
          type: string
        example: dagshub-docs
      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
              - id: 9
                type: dagshub
                config:
                  content_type: json
                  url: <webhook-url>
                events:
                - create
                - delete
                - push
                - pull_request
                - release
                active: true
                updated_at: 2022-09-14T10:01:11Z
                created_at: 2021-03-21T11:39:30Z
              - id: 11
                type: discord
                config:
                  content_type: json
                  url: https://discord.com/api/webhooks/awesome-webhook
                events:
                - fork
                - issues
                - pull_request
                - issue_comment
                active: true
                updated_at: 2022-09-14T10:01:12Z
                created_at: 2021-03-22T11:28:45Z
    post:
      tags:
      - Webhooks
      summary: Create a hook
      operationId: createHook
      parameters:
      - name: owner
        in: path
        description: owner of the repository
        required: true
        schema:
          type: string
        example: DAGsHub-Official
      - name: repo
        in: path
        description: name of the repository
        required: true
        schema:
          type: string
        example: dagshub-docs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/repo_hooks_body'
      responses:
        "201":
          description: Created
          content:
            application/json:
              example:
                id: 20
                type: discord
                config:
                  content_type: json
                  url: <webhook-url>
                events:
                - create
                - push
                active: true
                updated_at: 2022-08-29T11:31:22.453572732+08:00
                created_at: 2022-08-29T11:31:22.453569275+08:00
  /repos/{owner}/{repo}/hooks/{id}:
    delete:
      tags:
      - Webhooks
      summary: Delete a hook
      operationId: deleteHook
      parameters:
      - name: owner
        in: path
        description: owner of the repository
        required: true
        schema:
          type: string
        example: DAGsHub-Official
      - name: repo
        in: path
        description: name of the repository
        required: true
        schema:
          type: string
        example: dagshub-docs
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "204":
          description: "No Content, deleted successfully"
    patch:
      tags:
      - Webhooks
      summary: Edit a hook
      operationId: editHook
      parameters:
      - name: owner
        in: path
        description: owner of the repository
        required: true
        schema:
          type: string
        example: DAGsHub-Official
      - name: repo
        in: path
        description: name of the repository
        required: true
        schema:
          type: string
        example: dagshub-docs
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/hooks_id_body'
      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
                id: 20
                type: dagshub
                config:
                  content_type: json
                  url: <webhook-url>
                events:
                - push
                active: true
                updated_at: 2022-08-29T11:45:30.577057789+08:00
                created_at: 2022-08-29T11:31:22+08:00
components:
  schemas:
    Issues:
      type: array
      items:
        $ref: '#/components/schemas/Issue'
      x-schema-name: Issues
    PostIssue:
      type: object
      properties:
        title:
          $ref: '#/components/schemas/Title'
        body:
          $ref: '#/components/schemas/Body'
        assignee:
          $ref: '#/components/schemas/Assignee'
        milestone:
          $ref: '#/components/schemas/Milestone'
        labels:
          $ref: '#/components/schemas/Labels'
        closed:
          $ref: '#/components/schemas/Closed'
    Issue:
      required:
      - assignee
      - body
      - closed
      - labels
      - milestone
      - title
      type: object
      properties:
        id:
          type: integer
        number:
          type: integer
        user:
          $ref: '#/components/schemas/User'
        title:
          $ref: '#/components/schemas/Title'
        body:
          $ref: '#/components/schemas/Body'
        labels:
          type: array
          items:
            $ref: '#/components/schemas/Issue_labels'
        milestone:
          $ref: '#/components/schemas/Issue_milestone'
        assignee:
          $ref: '#/components/schemas/Issue_assignee'
        state:
          type: string
        comments:
          type: integer
        created_at:
          type: string
        updated_at:
          type: string
        pull_request:
          type: object
        closed:
          type: boolean
      example:
        id: 72
        number: 1
        state: open
        title: test issue
        body: ""
        user:
          id: 3
          username: user1
          full_name: ""
          email: fake@local
          avatar_url: https://secure.gravatar.com/avatar/0207f4280f6c1bd45e1a2ed7cb1cca3d
        labels:
        - bug
        assignee: null
        milestone: null
        comments: 1
        pull_request: null
        created_at: 2016-03-05T13:18:51-05:00
        updated_at: 2016-03-05T13:18:51-05:00
    PatchIssue:
      type: object
      properties:
        title:
          $ref: '#/components/schemas/Title'
        body:
          $ref: '#/components/schemas/Body'
        assignee:
          $ref: '#/components/schemas/Assignee'
        milestone:
          $ref: '#/components/schemas/Milestone'
        state:
          $ref: '#/components/schemas/State'
    CreateRepo:
      required:
      - name
      type: object
      properties:
        name:
          type: string
          description: name of the repository
          example: repo-name
        description:
          type: string
          description: A short description of the repository
        private:
          type: boolean
          description: "Either true to create a private repository, or false to create\
            \ a public one."
          default: false
        auto_init:
          type: boolean
          description: "Pass true to create an initial commit with README, .gitignore\
            \ and LICENSE."
          default: false
        project_template:
          type: string
          description: |
            Choose 'custom' to set .gitignore, license and readme, or 'none' for a completely empty repository.
            For other templates you may specify only the license.
          enum:
          - cookiecutter-dagshub-dvc
          - custom
          - none
          - notebook-template
        gitignores:
          type: string
          description: Desired language .gitignore templates to apply. Use the name
            of the templates.
          example: "Go, Sublime Text"
        license:
          type: string
          description: Desired LICENSE template to apply. Use the name of the template.
          example: MIT License
          enum:
          - Apache License 2.0
          - MIT License
          - Abstyles License
          - Academic Free License v1.1
          - Academic Free License v1.2
          - Academic Free License v2.0
          - Academic Free License v2.1
          - Academic Free License v3.0
          - Affero General Public License v1.0
          - Apache License 1.0
          - Apache License 1.1
          - Artistic License 1.0
          - Artistic License 2.0
          - BSD 2-clause License
          - BSD 3-clause License
          - BSD 4-clause License
          - Creative Commons CC0 1.0 Universal
          - Eclipse Public License 1.0
          - Educational Community License v1.0
          - Educational Community License v2.0
          - GNU Affero General Public License v3.0
          - GNU Free Documentation License v1.1
          - GNU Free Documentation License v1.2
          - GNU Free Documentation License v1.3
          - GNU General Public License v1.0
          - GNU General Public License v2.0
          - GNU General Public License v3.0
          - GNU Lesser General Public License v2.1
          - GNU Lesser General Public License v3.0
          - GNU Library General Public License v2.0
          - ISC license
          - Mozilla Public License 1.0
          - Mozilla Public License 1.1
          - Mozilla Public License 2.03
        readme:
          type: string
          description: Desired README template to apply. Use the name of the template.
          default: Default
    MigrateRepo:
      required:
      - clone_addr
      - user_id
      type: object
      properties:
        clone_addr:
          type: string
          description: Remote Git address (HTTP/HTTPS URL or local path)
        auth_username:
          type: string
          description: Authorization username
        auth_password:
          type: string
          description: Authorization password
        user_id:
          type: integer
          description: User ID who takes ownership of this repository
        repo_name:
          type: string
          description: Name of the repository
          example: repo-name
        mirror:
          type: boolean
          description: Repository will be a mirror (connected repository).
          default: false
        visibility:
          type: string
          description: Repository will be private or public.
          default: "false"
          enum:
          - private
          - public
        description:
          type: string
          description: Description of the repository
          example: '...'
    WebhookConfig:
      required:
      - content_type
      - url
      type: object
      properties:
        url:
          type: string
          description: A string defining the URL to which the payloads will be delivered.
          example: http://yourwebsite.io
        content_type:
          type: string
          description: A string defining the media type used to serialize the payloads.
          example: json
          enum:
          - json
          - form
        secret:
          type: string
          description: An optional string that's passed with the HTTP requests body.
          example: supersecretkey
      description: Key/value pairs to provide settings for this hook
    WebhookEvents:
      type: array
      description: Determines what events the hook is triggered format.
      example:
      - create
      - delete
      - fork
      - push
      - issues
      - issue_comment
      - pull_request
      - release
      items:
        type: object
      default:
      - push
      x-schema-name: WebhookEvents
    Title:
      type: string
      description: The title of the issue
      example: Test Issue from API documentation
    Body:
      type: string
      description: The contents of the issue.
      example: "This issue was made from the API using [DagsHub docs](https://dagshub.com/docs/api)"
    Assignee:
      type: string
      description: "Username for the user that this issue should be assigned to. \n\
        \n**Note:** Only users with write access can set the assignee for new issues.\
        \ \nThe assignee is silently dropped otherwise."
    Milestone:
      type: integer
      description: "The **ID** of the milestone to associate this issue with. \n\n\
        **Note:** Only users with write access can set the milestone for new issues.\
        \ \nThe milestone is silently dropped otherwise."
    Labels:
      type: array
      description: "Labels **ID** to associate with this issue. \n\n**Note:** Only\
        \ users with write access can set labels for new issues. \nLabels are silently\
        \ dropped otherwise."
      items:
        type: integer
      x-schema-name: Labels
    Closed:
      type: boolean
      description: Indicate initial issue state as closed (**true**) or open (**false**).
      example: true
      default: false
    User:
      type: object
      properties:
        id:
          type: integer
        login:
          type: string
        full_name:
          type: string
        avatar_url:
          type: string
        username:
          type: string
      additionalProperties: false
    State:
      type: string
      enum:
      - open
      - closed
    collaborators_collaborator_body:
      type: object
      properties:
        permission:
          type: string
          description: "The permission to grant the collaborator. Can be one of **read**,\
            \ **write** and **admin**."
          default: write
    repo_hooks_body:
      required:
      - config
      - type
      type: object
      properties:
        type:
          type: string
          description: The type of webhook
          example: discord
          enum:
          - dagshub
          - slack
          - discord
          - dingtalk
        config:
          $ref: '#/components/schemas/WebhookConfig'
        events:
          $ref: '#/components/schemas/WebhookEvents'
    hooks_id_body:
      type: object
      properties:
        config:
          $ref: '#/components/schemas/WebhookConfig'
        events:
          $ref: '#/components/schemas/WebhookEvents'
        active:
          type: boolean
          description: Weather the hook is actually triggered on pushes or not. Ignore
            this field to leave it unchanged.
    Issue_labels:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        color:
          type: string
        url:
          type: string
    Issue_milestone:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        state:
          type: string
        open_issues:
          type: integer
        closed_issues:
          type: integer
        closed_at:
          type: string
        due_on:
          type: string
      additionalProperties: false
    Issue_assignee:
      type: object
      properties:
        id:
          type: integer
        login:
          type: string
        full_name:
          type: string
        avatar_url:
          type: string
        username:
          type: string
      additionalProperties: false
  parameters:
    Username:
      name: username
      in: path
      description: A DagsHub username
      required: true
      schema:
        type: string
      example: nirbarazida
    Owner:
      name: owner
      in: path
      description: owner of the repository
      required: true
      schema:
        type: string
      example: DAGsHub-Official
    Repository:
      name: repo
      in: path
      description: name of the repository
      required: true
      schema:
        type: string
      example: dagshub-docs
    Index:
      name: index
      in: path
      description: the index of an issue or a pull request
      required: true
      schema:
        type: integer
    Orgname:
      name: orgname
      in: path
      description: A DagsHub organization name
      required: true
      schema:
        type: string
      example: DAGsHub-Official
    Ref:
      name: ref
      in: path
      description: The name of the commit/branch/tag
      required: true
      schema:
        type: string
        example: master
    Branch:
      name: branch
      in: path
      description: branch of the repository
      required: true
      schema:
        type: string
    Collaborator:
      name: collaborator
      in: path
      description: collaborator username
      required: true
      schema:
        type: string
    Sha:
      name: sha
      in: path
      description: a SHA1 of a commit
      required: true
      schema:
        type: string
        example: 9227a50146b3fd815fe864af99b984c77d06326a
  securitySchemes:
    basicAuth:
      type: http
      description: |
        Use your DagsHub username and password/access token.
      scheme: basic
    tokenAuth:
      type: apiKey
      description: |
        You can generate a token [here](http://dagshub.com/user/settings/tokens)
      name: token
      in: query
